#!/usr/bin/env bash

search_paths=(
  ~
  ~/x
  ~/.config
  ~/.config/nvim
  ~/Projects
  ~/Oxford
  ~/x/work
  ~/x/.dotfiles
  ~/Documents
  ~/LEGO
  ~/LEGO_MIGRATION_NEW
  ~/LEGO_migration_OLD
  ~/Projects/AI
)


if [[ $# -eq 1 ]]; then
  session=$1
else
  session=$(find "${search_paths[@]}" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | fzf)
fi

# session=~/x/personal

if [[ -z $session ]]; then
    exit 0
fi

session_name=$(basename "$session" | tr . _)

if ! tmux has-session -t "$session_name" 2> /dev/null; then 
    tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
#

# mine, same as on windows
echo "session: $session"
cd session

