#!/usr/bin/env bash

# Primeagensessionazer
# session=$(find ~ ~/x ~/Projects ~/Documents -mindepth 1 -maxdepth 1 -type d | fzf)
# session_name=$(basename "$session" | tr . _)

# if ! tmux has-session -t "$session_name" 2> /dev/null; then 
#     tmux new-session -s "$session_name" -c "$session" -d
# fi

# tmux switch-client -t "$session_name"
#

# mine, same as on windows
cd $(find ~ ~/x ~/Projects ~/x/work ~/Documents -mindepth 1 -maxdepth 1 -type d | fzf)
