#!/usr/bin/env bash

# find ~/Projects ~/Documents -mindepth 1 -maxdepth 1 -type d 
# find ~/Projects ~/Documents -mindepth 1 -maxdepth 1 -type d | fzf 
# session=$(find ~ ~/Projects ~/Documents -mindepth 1 -maxdepth 1 -type d | fzf)
session=$(find ~ ~/x ~/Projects ~/Documents -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)


# tmux has-session -t "$session_name"
# echo $(tmux has-session -t "$session_name")

if ! tmux has-session -t "$session_name" 2> /dev/null; then 
    tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
